import Head from "next/head";
import Layout from "@/components/Layout";
import Image from "next/image";
import profile_pic from "/public/images/profile/profile11.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title> Home page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center w-full text-dark min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className=" flex items-center justify-between w-full lg:flex-col">
            <div className=" w-1/2 h-auto lg:hidden md:inline-block md:w-full
            ">
              <Image src={profile_pic} alt="" className="w-full h-auto"
              priority
              sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              33vw "

              />
              {/* this priority key will avoid the lazy load, preload the images */}
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText text="Bringing a website to life through coding." className="xl:!text-6xl lg:!text-center lg:!text-5xl md:!text-3xl sm:text-xl " />
              <p className="my-4 text-base font-medium md:text-base sm:text-sm">
              Enthusiast software engineer adept in frontend development and Google Cloud technologies with 2 years of proven success. Demonstrated ability in fast and self-learning, bringing innovative solutions to fruition. Eager to apply expertise to drive success in software engineering roles, contributing to the continuous growth and advancement of the team and company. Passionate about staying abreast of emerging technologies to ensure cutting-edge solutions.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center   ">
                <Link
                  href="/SagarKrishna-resume.pdf"
                  target="_blank"
                  className=" items-center p-2.5 px-5 rounded-lg text-lg bg-dark text-light font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark hover:duration-500 dark:bg-light dark:text-dark dark:hover:text-light dark:hover:bg-dark dark:hover:border-light md:p-2 md:px-4 md:text-base sm:p-1.5 sm:px-2 sm:text-sm "
                  download={true}
                >
                  Download CV
                </Link>
                <Link
                  href="mailto:sagar22krishna03@gmail.com"
                  target="_blank"
                  className=" items-center p-2.5 px-5 rounded-lg text-lg bg-dark text-light font-semibold ml-6 hover:bg-light hover:text-dark border-2 border-bold border-transparent hover:border-dark hover:duration-500  dark:bg-light dark:text-dark dark:hover:text-light dark:hover:bg-dark dark:hover:border-light md:p-2 md:px-4 md:text-base sm:p-1.5 sm:px-2 sm:text-sm "
                >
                  {" "}
                  Hire Me
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
