import Head from "next/head";
import Layout from "@/components/Layout";
import Image from "next/image";
import profile_pic from "/public/images/profile/profile11.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
// import RaindropEffect from "@/components/RaindropEffect";

export default function Home() {
  return (
    <>
      <Head>
        <title> Home page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center w-full text-dark min-h-screen dark:text-light">
        {/* <RaindropEffect /> */}
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className=" flex items-center justify-between w-full lg:flex-col">
            <div
              className=" w-1/2 h-auto lg:hidden md:inline-block md:w-full
            "
            >
              <Image
                src={profile_pic}
                alt=""
                className="w-full h-auto"
                priority
                sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              33vw "
              />
              {/* this priority key will avoid the lazy load, preload the images */}
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Bringing a website to life through coding."
                className="xl:!text-6xl lg:!text-center lg:!text-5xl md:!text-3xl sm:text-xl "
              />
              <p className="my-4 text-base font-medium md:text-base sm:text-sm">
                Innovative software developer with <b>3+</b> years of experience
                specializing in <b>Android development</b>,{" "}
                <b>full-stack web development</b>, and <b>cloud computing</b>.
                Proficient in <b>Kotlin</b>, <b>Python</b>, <b>JavaScript</b>,{" "}
                <b>React.js</b>, <b>Node.js</b>, and <b>Google Cloud</b>, with a
                proven track record of delivering scalable and user-centric
                solutions. Passionate about leveraging emerging technologies to
                create intuitive and high-performance applications, from
                in-vehicle infotainment systems to full-stack web platforms.
                Eager to contribute to cutting-edge projects and drive
                technological advancements in software engineering.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center   ">
                <Link
                  href="/SagarKrishna-resume.pdf"
                  target="_blank"
                  className=" items-center p-2.5 px-5 rounded-lg text-lg bg-dark text-light font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark hover:duration-500 dark:bg-light dark:text-dark dark:hover:text-light dark:hover:bg-dark dark:hover:border-light md:p-2 md:px-4 md:text-base sm:p-1.5 sm:px-2 sm:text-sm "
                  download={true}
                >
                  Download CV
                </Link>
                <Link
                  href="mailto:sagar22krishna03@gmail.com"
                  target="_blank"
                  className=" items-center p-2.5 px-5 rounded-lg text-lg bg-dark text-light font-semibold ml-6 hover:bg-light hover:text-dark border-2 border-bold border-transparent hover:border-dark hover:duration-500  dark:bg-light dark:text-dark dark:hover:text-light dark:hover:bg-dark dark:hover:border-light md:p-2 md:px-4 md:text-base sm:p-1.5 sm:px-2 sm:text-sm "
                >
                  {" "}
                  Hire Me
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
